config/routes.rb
ThemeparcThemes::Application.routes.draw do
  root 'products#index', as: 'home'

  match 'themes/:theme_name', to: 'products#show', via: 'get'
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  validates :theme_title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Theme Parc
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  
  %body
    .container
      
      #header.row
        .col-xs-6.col-md-6
          %h1.logo.pull-left 
            =link_to image_tag('themeparc_logo.png'), home_path
        .col-xs-6.menu-toggle
          %a.pull-right{href: "#"}
            %i.icon-reorder
        
        %ul.nav.col-xs-12.col-md-6
          %li= link_to 'Themes', home_path
          %li= link_to 'Premium'
          %li= link_to 'Blog'
          %li= link_to 'Support'
      
      = yield

    #footer
      .container
        .row
          .col-xs-12.col-md-4
            %h4 From the blog
            %h5= link_to 'Improve Your Business Look'
            %p This is an excerpt from the blog. An excerpt from the blog.
            %p= link_to 'Read More ...'
          .col-xs-12.col-md-4
            %h4 Find us on
            %a{:href => ""} 
              %i.icon-facebook-sign.icon-3x
            %a{:href => ""}
              %i.icon-twitter-sign.icon-3x
            %a{:href => ""}
              %i.icon-google-plus-sign.icon-3x
          .col-xs-12.col-md-4
            %h4 Connect for updates
            %form#subscribe
              %input.col-sm-12{type: "text", placeholder: "Email"}/ 
              %input.tp-btn{type: "submit", value: "Subscribe"}

app/views/products/index.html.haml
#product-featured.row
  .product.col-xs-12.col-lg-10.col-lg-offset-1
    %a{:href => "themes/theme_name"} 
      =image_tag 'http://i.istockimg.com/file_thumbview_approve/20327056/2/stock-photo-20327056-portland-oregon-sign.jpg', class: 'img-responsive', width: "100%"
#products.row
  .col-lg-10.col-lg-offset-1
    .row
      .product.col-xs-12.col-sm-6.col-md-6
        %a{:href => "#"} 
          =image_tag 'http://placehold.it/723x450', class: 'img-responsive'
        .description
          %h4= link_to 'Theme Title'
          %p $50.00
      .product.col-xs-12.col-sm-6.col-md-6
        %a{:href => "#"} 
          =image_tag 'http://placehold.it/723x450', class: 'img-responsive'
        .description
          %h4= link_to 'Theme Title'
          %p $50.00
      .product.col-xs-12.col-sm-6.col-md-6
        %a{:href => "#"} 
          =image_tag 'http://placehold.it/723x450', class: 'img-responsive'
        .description
          %h4= link_to 'Theme Title'
          %p $50.00
      .product.col-xs-12.col-sm-6.col-md-6
        %a{:href => "#"} 
          =image_tag 'http://placehold.it/723x450', class: 'img-responsive'
        .description
          %h4= link_to 'Theme Title'
          %p $50.00

app/views/products/show.html.haml
#product-show
  .row
    .col-xs-12.col-xs-12.col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
      %h2 Theme Title
      %p 
        %a{href: "#"} Live Demo
      =image_tag 'http://placehold.it/750x400', class: 'img-responsive'
      .description
        .panel.panel-default
          .panel-heading Purchase this theme
          .panel-body
            %h4.pull-left $20.00
            %a.pull-right.tp-btn{href: "#"} Checkout 

            %p.clear-both Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.
            
  